development:
  password: <PASSWORD>
  theme_id: "<THEME_ID>"
  store: <STORE_URL>
  directory: dist/
  ignore_files:
    - assets/theme.bundle.js
    - assets/application.bundle.js
    - assets/dropdown.bundle.js
    - assets/theme-cart.bundle.js
    - assets/alert-toast.bundle.js